In [1]:
import numpy as np

In [4]:
array=np.array([1,2,3,4,5])
print(type(array))

<class 'numpy.ndarray'>


In [7]:
array2=array+1
array2

array([2, 3, 4, 5, 6])

In [8]:
array2+array

array([ 3,  5,  7,  9, 11])

In [9]:
array2*array


array([ 2,  6, 12, 20, 30])

In [10]:
array.shape

(5,)

In [11]:
print(array)

[1 2 3 4 5]


In [4]:
tang=np.array([1,2,3,4,5])
tang

array([1, 2, 3, 4, 5])

In [9]:
tang[-2:-1]

array([4])

In [31]:
chen=np.array([[1,2,3],
               [1,2,3],
               [1,2,3]])
chen

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [37]:
chen.ndim

2

In [33]:
chen.shape

(3, 3)

In [34]:
jie=np.arange(0,100,10)
jie

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
type(jie)

numpy.ndarray

In [36]:
jie.ndim

1

In [46]:
demo=np.array([1,2,3],[2,31,2],[4,5,3])
demo

array([[ 1,  2,  3],
       [ 2, 31,  2],
       [ 4,  5,  3]])

In [47]:
demo.ndim

2

In [61]:
cc=np.array([[[1, 2, 3,4],[1, 2, 3,4],[1, 2, 3,4],[1, 2, 3,4]],[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],[1, 2, 3,4]],[[1, 2, 3,4],[1, 2, 3,4],[1, 2, 3,4],[1, 2, 3,4]],[[1, 2, 3,4],[1, 2, 3,4],[1, 2, 3,4],[1, 2, 3,4]]])
cc

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [62]:
cc.ndim

3

In [63]:
cc.shape

(4, 4, 4)

In [71]:
#import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)

[[0 0]
 [0 0]
 [0 0]]


In [74]:
x = np.zeros([5],dtype=int) 
x

array([0, 0, 0, 0, 0])

In [8]:
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
x[[0,1,2],  [0,1,0]] 
y

array([1, 4, 5])

In [2]:
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
y = x[[0,1,2],  [0,1,0]]  
y

array([1, 4, 5])

In [4]:
x.ndim

2

In [5]:
x.shape

(3, 2)